[package]
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]
name = "fugu-shell"
version = "0.1.0"
[dependencies]
env_logger = "0.4.3"
lazy_static = "0.2.10"
libc = "*"
log = "0.3.8"
termion = "1.5.1"
walkdir = "2.0.1"
